# Generated by Django 5.2.3 on 2025-07-17 13:31

import apps.utils.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Kirgan vaqti')),
                ('exit_time', models.DateTimeField(auto_now=True, verbose_name='Chiqqan vaqti')),
                ('area_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Kirgan vaqti')),
                ('exit_time', models.DateTimeField(auto_now=True, verbose_name='Chiqqan vaqti')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzili')),
                ('port', models.IntegerField(default=554)),
                ('username', models.CharField(max_length=50, verbose_name='Kamera login')),
                ('password', models.CharField(max_length=120, verbose_name='Kamera parol')),
                ('type', models.CharField(choices=[('IN', 'Kiruvchi'), ('OUT', 'Chiquvchi')], max_length=3, verbose_name='Turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolligi')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Yaratilgan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExceptionalTransports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Kirgan vaqti')),
                ('exit_time', models.DateTimeField(auto_now=True, verbose_name='Chiqqan vaqti')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Davlat raqami')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Egasining ismi')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Kirgan vaqti')),
                ('exit_time', models.DateTimeField(auto_now=True, verbose_name='Chiqqan vaqti')),
                ('plate_number', models.CharField(max_length=20, verbose_name='Davlat raqami')),
                ('owner_name', models.CharField(blank=True, max_length=255, verbose_name='Egasining ismi')),
                ('no_plate_number', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Kirgan vaqti')),
                ('exit_time', models.DateTimeField(auto_now=True, verbose_name='Chiqqan vaqti')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=100, verbose_name="To'liq ism")),
                ('phone', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[apps.utils.validators.validate_phone_number], verbose_name='Telefon raqam')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Kirgan vaqti')),
                ('exit_time', models.DateTimeField(auto_now=True, verbose_name='Chiqqan vaqti')),
                ('has_fine', models.BooleanField(default=False, verbose_name='Jarima mavjudmi?')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langanmi?")),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Kirgan vaqti')),
                ('photo', models.ImageField(upload_to='exit_photos/', verbose_name='Chiqish rasmi')),
                ('exit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Chiqish vaqti')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'langan summa")),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Kvitansiya fayli')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Kirgan vaqti')),
                ('exit_time', models.DateTimeField(auto_now=True, verbose_name='Chiqqan vaqti')),
                ('plate_number', models.CharField(blank=True, max_length=30, null=True)),
                ('no_plate_number', models.BooleanField(default=False)),
                ('photo_front', models.ImageField(blank=True, null=True, upload_to='entries/front/')),
                ('photo_rear', models.ImageField(blank=True, null=True, upload_to='entries/rear/')),
                ('photo_left', models.ImageField(blank=True, null=True, upload_to='entries/left/')),
                ('photo_right', models.ImageField(blank=True, null=True, upload_to='entries/right/')),
                ('is_manual', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='apps.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
