# Generated by Django 5.2.3 on 2025-06-18 19:09

import apps.utils.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzili')),
                ('port', models.IntegerField(default=554)),
                ('username', models.CharField(max_length=50, verbose_name='Kamera login')),
                ('password', models.CharField(max_length=120, verbose_name='Kamera parol')),
                ('type', models.CharField(choices=[('IN', 'Kiruvchi'), ('OUT', 'Chiquvchi')], max_length=3, verbose_name='Turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolligi')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Yaratilgan')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Davlat raqami')),
                ('owner_name', models.CharField(blank=True, max_length=255, verbose_name='Egasining ismi')),
                ('is_evacuator', models.BooleanField(default=False, verbose_name='Evakuatormi?')),
                ('is_whitelisted', models.BooleanField(default=False, verbose_name='Doimiy kiruvchi (ruxsatli)')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=100, verbose_name="To'liq ism")),
                ('phone', models.CharField(max_length=13, unique=True, validators=[apps.utils.validators.validate_phone_number], verbose_name='Telefon raqam')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Adminmi?')),
                ('is_guard', models.BooleanField(default=False, verbose_name='Qorovulmi?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_fine', models.BooleanField(default=False, verbose_name='Jarima mavjudmi?')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langanmi?")),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ExitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='exit_photos/', verbose_name='Chiqish rasmi')),
                ('exit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Chiqish vaqti')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'langan summa")),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Kvitansiya fayli')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='entry_photos/', verbose_name='Kirish rasmi')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kirish vaqti')),
                ('is_manual', models.BooleanField(default=False, verbose_name="Qo'lda kiritilganmi?")),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.vehicle')),
            ],
        ),
    ]
