# Generated by Django 5.2.3 on 2025-06-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionalTransports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Davlat raqami')),
                ('owner_name', models.CharField(blank=True, max_length=255, verbose_name='Egasining ismi')),
            ],
        ),
    ]
