# Generated by Django 5.2.3 on 2025-07-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exitlog',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='exitlog',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='exitlog',
            name='exit_time',
        ),
        migrations.RemoveField(
            model_name='exitlog',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='exitlog',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='exitlog',
            name='receipt',
        ),
        migrations.AddField(
            model_name='exitlog',
            name='entry',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='apps.entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exitlog',
            name='photo_front_exit',
            field=models.ImageField(blank=True, null=True, upload_to='exits/front/'),
        ),
        migrations.AddField(
            model_name='exitlog',
            name='photo_left_exit',
            field=models.ImageField(blank=True, null=True, upload_to='exits/left/'),
        ),
        migrations.AddField(
            model_name='exitlog',
            name='photo_rear_exit',
            field=models.ImageField(blank=True, null=True, upload_to='exits/rear/'),
        ),
        migrations.AddField(
            model_name='exitlog',
            name='photo_right_exit',
            field=models.ImageField(blank=True, null=True, upload_to='exits/right/'),
        ),
        migrations.AddField(
            model_name='exitlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2011-09-01T13:20:30+03:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exitlog',
            name='total_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exitlog',
            name='yard_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
