# Generated by Django 5.2.3 on 2025-07-21 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_exitlog_approved_by_remove_exitlog_entry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='daily_fee',
            field=models.PositiveIntegerField(default=10000, help_text='1 kunlik jarima maydon to‘lovi (so‘mda)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='area',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='apps.area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='area_id',
            field=models.IntegerField(unique=True),
        ),
    ]
