# Generated by Django 5.2.3 on 2025-07-21 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_area_daily_fee_vehicle_area_alter_area_area_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='area',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='apps.area'),
            preserve_default=False,
        ),
    ]
