# Generated by Django 5.2.3 on 2025-07-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_exitlog_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='fine_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='yard_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
