# Generated by Django 5.2.3 on 2025-07-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_entry_fine_paid_entry_yard_fee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitlog',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
