# Generated by Django 5.2.3 on 2025-07-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_exitlog_is_manual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exitlog',
            old_name='is_manual',
            new_name='is_manual_entry',
        ),
        migrations.AddField(
            model_name='exitlog',
            name='is_manual_exit',
            field=models.BooleanField(default=False),
        ),
    ]
