# Generated by Django 5.2.3 on 2025-07-24 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_rename_is_manual_exitlog_is_manual_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitlog',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit', to='apps.entry'),
        ),
    ]
