# Generated by Django 5.2.3 on 2025-08-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_exitlog_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='entries/front/2025-08-04/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='photo_left',
            field=models.ImageField(blank=True, null=True, upload_to='entries/left/2025-08-04/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='photo_rear',
            field=models.ImageField(blank=True, null=True, upload_to='entries/rear/2025-08-04/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='photo_right',
            field=models.ImageField(blank=True, null=True, upload_to='entries/right/2025-08-04/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Egasining ismi'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Davlat raqami'),
        ),
    ]
