# Generated by Django 5.2.3 on 2025-08-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_entry_photo_front_alter_entry_photo_left_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_name',
        ),
        migrations.AlterField(
            model_name='entry',
            name='photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='entries/front/2025-08-06/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='photo_left',
            field=models.ImageField(blank=True, null=True, upload_to='entries/left/2025-08-06/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='photo_rear',
            field=models.ImageField(blank=True, null=True, upload_to='entries/rear/2025-08-06/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='photo_right',
            field=models.ImageField(blank=True, null=True, upload_to='entries/right/2025-08-06/'),
        ),
    ]
